### Create a branch
# Expected response
# HTTP/1.1 201 Created, with the address matching the id returned
POST http://localhost:8080/api/branch
Content-Type: application/json

{
    "branchNo": "B888",
    "street": "101 Main Street",
    "city": "Victoria",
    "postCode": "V0V M3M"
}

### Get the Branch Address With the Specific ID
# Expected response
# HTTP/1.1 200 OK, with the address matching the id returned
GET http://localhost:8080/api/branch/address/B888

### Update a branch
# Expected response
# HTTP/1.1 204 No Content
PUT http://localhost:8080/api/branch/B888
Content-Type: application/json

{
    "branchNo": "B888",
    "street": "101 Main Street",
    "city": "Victoria",
    "postCode": "M3M V0V"
}