### Add a Client
# Expected response
# HTTP/1.1 201 Created, with the address matching the id returned
POST http://localhost:8080/api/client
Content-Type: application/json

{
    "clientNo": "T123",
    "firstName": "John",
    "lastName": "Doe",
    "telephoneNo": "123 6789",
    "street": "123 Main St",
    "city": "New York",
    "email": "john.doe@example.com",
    "prefType": "Type",
    "maxRent": 1000
}


### Get the Client info With the Specific ID
# Expected response
# HTTP/1.1 200 OK, with the branch matching the id returned
GET http://localhost:8080/api/client/T123 


### Get all Clients
# Expected response
# HTTP/1.1 200 OK, with a list of clients returned
GET http://localhost:8080/api/client


### Update a Client
# Expected response
# HTTP/1.1 201 Created, with the address matching the id returned
PUT http://localhost:8080/api/client/T123
Content-Type: application/json

{
    "clientNo": "T123",
    "firstName": "John",
    "lastName": "Doe",
    "telephoneNo": "123 6789",
    "street": "456 Main St",
    "city": "New York",
    "email": "john.doe@example.com",
    "prefType": "Type",
    "maxRent": 1000
}
