### Create a Staff
# POST /api/staff
# Expected response, HTTP/1.1 201 CREATED
POST http://localhost:8080/api/staff
Content-Type: application/json

{
    "staffNo": "S128",
    "fname": "John",
    "lname": "Doe",
    "position": "Manager",
    "sex": "Male",
    "dob": "1990-01-10",
    "salary": 50000,
    "branchNo": "B003",
    "telephone": "1234567890",
    "mobile": "9876543210",
    "email": "john.doe@example.com"
}

### List All Staffs Endpoint Test
# Expected response
# HTTP/1.1 200 OK, with a list of staffs
GET http://localhost:8080/api/staff

### Get the Staff With the Specific ID
# Expected response
# HTTP/1.1 200 OK, with the staff matching the id
GET http://localhost:8080/api/staff/S128

### Get Invalid Staff With A Invalid ID
# Expected response
# HTTP/1.1 404 NOT_FOUND, with timestamp and message
GET http://localhost:8080/api/staff/SL415555

### Update a staff
# Expected response
# HTTP/1.1 204 NO_CONTENT
# Run POST http://localhost:8080/api/staff test (at the top) to ensure S128 exists
PUT http://localhost:8080/api/staff/S128
Content-Type: application/json

{
    "staffNo": "S128",
    "fname": "John",
    "lname": "Doe",
    "position": "Manager",
    "sex": "Male",
    "dob": "1990-01-10",
    "salary": 60000,
    "branchNo": "B003",
    "telephone": "1234567890",
    "mobile": "9876543210",
    "email": "john.doe@example.com"
}

### DELETE A Staff By ID With No Constraint
# Expected response
# HTTP/1.1 204 NO_CONTENT, or 404 if staff not exists
# Run POST http://localhost:8080/api/staff test (at the top) to ensure 204 NO_CONTENT
DELETE http://localhost:8080/api/staff/S128

### DELETE A Staff By ID With Foreign Key Constraint
# Expected response
# HTTP/1.1 409 with error and message explaining the cause 
DELETE http://localhost:8080/api/staff/SL41

